[package]
name = "rust_excel_to_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
rusqlite = { version = "0.31", features = ["bundled"] }
xlsxwriter = "0.6.1"
rayon = "1.8"